#!/usr/bin/env python3
"""Build a token table for the Dictionary value codec (_DICT_COMPRESS).

Input: one or more text files with one sample value per line (the kind of values
your dictionaries hold). Output: a C++ header usable as the default table
(src/DictionaryCodecTable.h) or as a custom one via
    -D _DICT_CODEC_TABLE='"my_table.h"'

Selection is greedy: each round encodes the corpus with the tokens chosen so far
(longest match first, as the library does), counts the substrings left over in
literal runs, and adds the one that saves the most bytes (occurrences x (length - 1)).

Table rules the library relies on (enforced here):
  - at most 127 tokens (codes 0x80..0xFE; 0xFF escapes a literal high byte)
  - printable ASCII, 2..MAXLEN bytes each
  - sorted by first byte, longest first within one first byte

Usage:
  make_codec_table.py corpus.txt [more.txt ...] [--tokens 127] [--maxlen 8] [-o out.h]
"""
import argparse
import collections
import sys


def encode_runs(s, table_by_first):
    """Greedy longest-match encode; return the literal runs left over."""
    runs, cur, i, n = [], [], 0, len(s)
    while i < n:
        match = None
        for tok in table_by_first.get(s[i], ()):
            if s.startswith(tok, i):
                match = tok
                break
        if match:
            if cur:
                runs.append("".join(cur))
                cur = []
            i += len(match)
        else:
            cur.append(s[i])
            i += 1
    if cur:
        runs.append("".join(cur))
    return runs


def encoded_size(s, table_by_first):
    size, i, n = 0, 0, len(s)
    while i < n:
        match = None
        for tok in table_by_first.get(s[i], ()):
            if s.startswith(tok, i):
                match = tok
                break
        if match:
            i += len(match)
            size += 1
        else:
            size += 2 if ord(s[i]) >= 0x80 else 1
            i += 1
    return size


def by_first(tokens):
    table = collections.defaultdict(list)
    for t in tokens:
        table[t[0]].append(t)
    for v in table.values():
        v.sort(key=len, reverse=True)
    return table


def select(corpus, count, maxlen):
    tokens = []
    for _ in range(count):
        table = by_first(tokens)
        gains = collections.Counter()
        for s in corpus:
            for run in encode_runs(s, table):
                m = len(run)
                for L in range(2, min(maxlen, m) + 1):
                    for i in range(m - L + 1):
                        sub = run[i:i + L]
                        if all(0x20 <= ord(ch) < 0x7F for ch in sub):
                            gains[sub] += L - 1
        if not gains:
            break
        best, gain = gains.most_common(1)[0]
        if gain < 4:
            break
        tokens.append(best)
    return tokens


def c_literal(tok):
    out = []
    for ch in tok:
        if ch in '"\\?':
            out.append("\\" + ch)
        else:
            out.append(ch)
    return '"' + "".join(out) + '"'


def emit(tokens, source_note):
    tokens = sorted(tokens, key=lambda t: (ord(t[0]), -len(t), t))
    offs, pos = [], 0
    for t in tokens:
        offs.append(pos)
        pos += len(t)
    offs.append(pos)
    lines = [
        "// Token table for the Dictionary value codec (_DICT_COMPRESS).",
        "// Generated by extras/codec/make_codec_table.py" + (" from " + source_note if source_note else "") + ".",
        "// Rules: at most 127 tokens, sorted by first byte and longest first within",
        "// one first byte. Token i is written as the byte 0x80 + i.",
        "#pragma once",
        "",
        "namespace DictCodecTable {",
        "",
        "static const uint8_t COUNT = %d;" % len(tokens),
        "",
        "static const char DATA[] PROGMEM =",
    ]
    for i in range(0, len(tokens), 8):
        lines.append("  " + " ".join(c_literal(t) for t in tokens[i:i + 8]))
    lines[-1] += ";"
    lines += ["", "static const uint16_t OFFS[COUNT + 1] PROGMEM = {"]
    for i in range(0, len(offs), 12):
        lines.append("  " + ", ".join(str(o) for o in offs[i:i + 12]) + ("," if i + 12 < len(offs) else ""))
    lines += ["};", "", "} // namespace DictCodecTable", ""]
    return "\n".join(lines)


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("corpus", nargs="+")
    ap.add_argument("--tokens", type=int, default=127)
    ap.add_argument("--maxlen", type=int, default=8)
    ap.add_argument("--note", default="", help="text for the header comment")
    ap.add_argument("-o", "--out")
    a = ap.parse_args()
    if not 1 <= a.tokens <= 127:
        sys.exit("--tokens must be 1..127")
    if not 2 <= a.maxlen <= 32:
        sys.exit("--maxlen must be 2..32")
    corpus = []
    for path in a.corpus:
        with open(path, encoding="utf-8", errors="replace") as f:
            corpus += [line.rstrip("\r\n") for line in f if line.strip()]
    tokens = select(corpus, a.tokens, a.maxlen)
    raw = sum(len(s.encode("utf-8")) for s in corpus)
    packed = sum(min(encoded_size(s, by_first(tokens)), len(s)) for s in corpus)
    sys.stderr.write("%d tokens; corpus %d -> %d bytes (%.1f%%)\n"
                     % (len(tokens), raw, packed, 100.0 * packed / max(raw, 1)))
    text = emit(tokens, a.note)
    if a.out:
        with open(a.out, "w", newline="\n") as f:
            f.write(text)
    else:
        sys.stdout.write(text)


if __name__ == "__main__":
    main()
