// Token table for the Dictionary value codec (_DICT_COMPRESS).
// Generated by extras/codec/make_codec_table.py from English prose and synthetic configuration values.
// Rules: at most 127 tokens, sorted by first byte and longest first within
// one first byte. Token i is written as the byte 0x80 + i.
#pragma once

namespace DictCodecTable {

static const uint8_t COUNT = 127;

static const char DATA[] PROGMEM =
  " the " " a" " b" " c" " f" " g" " i" " p"
  " s" " u" " w" " y" ") " ", " ".gov" ".io"
  ".uk" ". " ".1" ".b" "/api/v" "192.168." "172.16." "10.0."
  "://" ": " "a " "ab" "ac" "ad" "ag" "al"
  "an" "ap" "ar" "as" "at" "bu" "clu" "ce"
  "ch" "co" "cu" "d " "de" "di" "do" "e "
  "ec" "ed" "el" "en" "er" "es" "ex" "ff"
  "fi" "gra" "g " "https://" "h " "ho" "ht" "ic"
  "if" "il" "in" "is" "it" "k " "l " "le"
  "li" "lo" "mqtt" "m " "ma" "mb" "me" "mo"
  "mp" "n " "ne" "ng" "no" "nt" "obj" "of"
  "ol" "on" "op" "or" "ou" "pro" "po" "qu"
  "r " "re" "ri" "ro" "s " "s." "s/" "se"
  "si" "sp" "ss" "st" "su" "tion" "to " "typ"
  "t " "te" "th" "ti" "to" "tp" "tr" "ub"
  "ul" "un" "ur" "ve" "vi" "wh" "y ";

static const uint16_t OFFS[COUNT + 1] PROGMEM = {
  0, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25,
  27, 29, 31, 35, 38, 41, 43, 45, 47, 53, 61, 68,
  73, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96,
  98, 100, 102, 105, 107, 109, 111, 113, 115, 117, 119, 121,
  123, 125, 127, 129, 131, 133, 135, 137, 139, 141, 144, 146,
  154, 156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176,
  178, 180, 182, 186, 188, 190, 192, 194, 196, 198, 200, 202,
  204, 206, 208, 211, 213, 215, 217, 219, 221, 223, 226, 228,
  230, 232, 234, 236, 238, 240, 242, 244, 246, 248, 250, 252,
  254, 256, 260, 263, 266, 268, 270, 272, 274, 276, 278, 280,
  282, 284, 286, 288, 290, 292, 294, 296
};

} // namespace DictCodecTable
